---
title: "Untitled"
author: "James Choi"
date: "Last compiled: `r Sys.Date()`"
output: 
  html_document
editor_options:
  chunk_output_type:
    console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center', 
                      tidy.opts=list(width.cutoff=80), tidy=TRUE,
                      results='hold')
knitr::opts_knit$set(root.dir = 'D:/MiamiProject/Park_snSeq_SuperiorColliculus/')
```


```{r libraries}
library(Seurat)
library(ggplot2)
library(dplyr)
library(SingleCellExperiment)
library(scuttle)
library(scran)
```


```{r}
results_out <- 'results/Excitatory-neuron_cluster-analysis'
dir.create(path = results_out)
umap_theme <- theme_bw() + 
  theme(panel.grid = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank())
```

```{r load-data}
sc <- readRDS(file = 'data/allages_dims20_res0.3_final_JSC.rds')
jsc <- readRDS(file = 'data/SC_20200103.rds')
```

```{r metadata}
# Idents(sc) <- 'integrated_snn_res.0.3'
# sc <- sc[,sc$celltype != 'Excluded']
sc$orig.ident <- factor(
  x = sc$orig.ident,
  levels = c('e19_cells_premrna_t1',
             'p4_cells_premrna_t1',
             'p8_cells_premrna_t1',
             'p21_cells_premrna_t1')
)
sc$Time <- factor(
  x = sc$Time,
  levels = c('E19','P4','P8','P21')
)
```

```{r sc-umap, fig.height=4, fig.width=10}
p.celltype <- DimPlot(sc, group.by = 'celltype', label = TRUE, shuffle = TRUE) + umap_theme
p.time <- DimPlot(sc, group.by = 'Time', shuffle = TRUE) + umap_theme
p.celltype | p.time
```

```{r}
DefaultAssay(sc) <- 'RNA'
Idents(sc) <- 'integrated_snn_res.0.3'
sc.default.deg <- FindAllMarkers(sc, assay = 'RNA', logfc.threshold = 0.5, only.pos = TRUE)
```

```{r subset-excitatory-neurons}
ex.neurons <- sc[,sc$celltype == 'Excitatory Neuron']
ex.neurons$Time <- factor(
  x = ex.neurons$Time,
  levels = c('E19','P4','P8','P21')
)
```

```{r umi-qc}
ex.neurons_sce <- SingleCellExperiment(
  assays = list(counts = ex.neurons@assays$RNA@counts)
)
colData(ex.neurons_sce) <- cbind(colData(ex.neurons_sce), ex.neurons@meta.data)
ex.neurons_sce <- logNormCounts(
  x = ex.neurons_sce, 
  size.factors = NULL,
  transform = 'log',
  pseudo.count = 1
)
VlnPlot(ex.neurons, group.by = 'orig.ident', pt.size = 0, features = c('nCount_RNA','nFeature_RNA'))
```

```{r}
hvg <- modelGeneVar(
  x = ex.neurons_sce,
  assay.type = 'logcounts',
  block = ex.neurons_sce$orig.ident,
  # lowess = FALSE
)
per.block <- hvg$per.block
par(mfrow = c(2,2))
for (i in seq_along(per.block)) {
  hvg.i <- per.block[[i]]
  plot(hvg.i$mean, hvg.i$total, xlab = "Mean log-expression", ylab = "Variance",
       main = names(per.block)[i])
  curve(metadata(hvg.i)$trend(x), col = "blue", add = TRUE)
}
par(mfrow = c(1,1))
```

```{r}
ex.neurons <- NormalizeData(ex.neurons)
VariableFeatures(ex.neurons) <- getTopHVGs(
  stats = hvg,
  fdr.threshold = 0.05
)
ex.neurons <- ex.neurons %>% 
  ScaleData() %>% 
  RunPCA() %>% 
  FindNeighbors(dims = 1:10) %>% 
  FindClusters(resolution = 0.5) %>% 
  RunUMAP(dims = 1:10)
```

```{r}
p.cluster <- DimPlot(ex.neurons, label = TRUE, shuffle = TRUE) + umap_theme
p.time <- DimPlot(ex.neurons, group.by = 'Time', shuffle = TRUE) + umap_theme
p.cluster | p.time
```



```{r}
ex.neurons <- SplitObject(ex.neurons, split.by = 'Time')
ex.neurons <- lapply(ex.neurons, SCTransform)
anchor.feats <- SelectIntegrationFeatures(object.list = ex.neurons)
ex.neurons <- PrepSCTIntegration(ex.neurons, anchor.features = anchor.feats)
anchors <- FindIntegrationAnchors(ex.neurons, anchor.features = anchor.feats, normalization.method = 'SCT')
ex.neurons <- IntegrateData(anchorset = anchors, normalization.method = 'SCT')
ex.neurons <- ex.neurons %>% 
  RunPCA() %>% 
  FindNeighbors(dims = 1:15) %>% 
  FindClusters(resolution = 0.4) %>% 
  RunUMAP(dims = 1:15)
```

```{r}
ex.de <- FindAllMarkers(ex.neurons,
                        assay = 'RNA',
                        only.pos = TRUE,
                        logfc.threshold = 0.5)
```


```{r}
ex.neurons <- SplitObject(ex.neurons, split.by = 'orig.ident')
for (i in 1:length(ex.neurons)) {
  tmp_nfeat <- median(ex.neurons[[i]]$nFeature_RNA)
  ex.neurons[[i]] <- ex.neurons[[i]] %>% 
    NormalizeData() %>% 
    FindVariableFeatures(nfeatures = tmp_nfeat) %>% 
    ScaleData()
}
anchor.feats.n <- floor(min(sapply(ex.neurons, FUN = function(x) median(x$nFeature_RNA))))
anchor.feats <- SelectIntegrationFeatures(
  object.list = ex.neurons,
  nfeatures = anchor.feats.n
)
ex.neurons <- FindIntegrationAnchors(
  object.list = ex.neurons,
  assay = 'RNA',
  anchor.features = 
)
```

```{r}
ex.neurons <- RunPCA(object = ex.neurons)
ElbowPlot(object = ex.neurons, ndims = 40)
```

```{r, fig.height=4, fig.width=10}
ex.neurons <- ex.neurons %>% 
  FindNeighbors(dims = 1:15) %>% 
  FindClusters(resolution = 0.5) %>% 
  RunUMAP(dims = 1:15)
p.cluster <- DimPlot(ex.neurons, group.by = 'SCT_snn_res.0.5', label = TRUE, shuffle = TRUE) + theme_bw()
p.time <- DimPlot(ex.neurons, group.by = 'Time', shuffle = TRUE) + theme_bw()
p.cluster | p.time
```

