---
title: "Superior colliculus integrated cluster analysis"
author: "James Choi"
date: "Last compiled: `r Sys.Date()`"
output: 
  html_document
editor_options:
  chunk_output_type: 
    console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center', 
                      tidy.opts=list(width.cutoff=80), tidy=TRUE,
                      results='hold')
knitr::opts_knit$set(root.dir = 'D:/MiamiProject/Park_snSeq_SuperiorColliculus/')
```


## Setup

```{r libraries}
library(Seurat)
library(ggplot2)
library(dplyr)
library(SingleCellExperiment)
library(scran)
library(scuttle)
```

```{r samplesheet}
samplesheet <- read.csv(file = 'data/samplesheet.csv')
sample_names <- samplesheet$SampleName
```

```{r directories}
counts_path <- 'data/qc_filtered_feature_bc_matrix/'
results_out <- 'results/Integrated-cluster-analysis/'
dir.create(path = results_out)
```

```{r utils-params}
shuffle_rows <- function(df) {
  df[sample(1:nrow(df), size = nrow(df), replace = FALSE),]
}
umap_theme <- theme_bw() + 
  theme(panel.grid = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank())
time.cols <- c("#dd4539","#d9b123","#68c545","#514fd1")
celltype.cols <- RColorBrewer::brewer.pal(n = 12, name = 'Paired')
neuron.cols <- c("#c2444c","#e14327","#be6231","#de8d26","#debc22","#b99f3e","#a6c336","#6f9a3e","#63d135","#59c251","#4db873","#36dbbc","#7b85dc","#6074eb","#554ea8","#6934c4","#9253ea","#412070","#542298","#ac69d3","#ce4ce2","#d980cc","#cc4bb5","#df35bd","#92337c","#d54681")
```


## Import data

```{r import-counts}
counts <- vector(mode = 'list', length = length(sample_names))
names(counts) <- sample_names
for (i in 1:length(sample_names)) {
  counts[[i]] <- readRDS(file = paste0(counts_path, sample_names[i], '.rds'))
}
```

```{r set-unique-barcodes}
for (i in 1:length(counts)) {
  colnames(counts[[i]]) <- paste(colnames(counts[[i]]), sample_names[i], sep = '_')
}
```


## Simple merge 

```{r simple-merge}
# sc <- Reduce(f = cbind, x = counts)
sc <- vector(mode = 'list', length = length(sample_names))
names(sc) <- sample_names
for (i in 1:length(sample_names)) {
  sc[[i]] <- CreateSeuratObject(
    counts = counts[[i]], 
    project = sample_names[i]
  )
  sc[[i]] <- PercentageFeatureSet(
    object = sc[[i]],
    pattern = '^mt-',
    col.name = 'percent_mt'
  )
  sc[[i]] <- PercentageFeatureSet(
    object = sc[[i]],
    pattern = '^Rp[ls]',
    col.name = 'percent_rp'
  )
}
sc <- Reduce(f = merge, x = sc)
sc <- sc %>% 
  NormalizeData() %>% 
  FindVariableFeatures(nfeatures = 3000) %>% 
  ScaleData() %>% 
  RunPCA()
sc <- sc %>% 
  FindNeighbors(dims = 1:15) %>% 
  FindClusters(resolution = 0.8) %>% 
  RunUMAP(dims = 1:15)
```

```{r simple-umap}
p.time <- DimPlot(sc, group.by = 'Time', shuffle = TRUE) + umap_theme
p.cluster <- DimPlot(sc, group.by = 'seurat_clusters', label = TRUE, label.size = 4, repel = TRUE) + umap_theme + NoLegend()
p.metadata <- sc@meta.data %>% 
  mutate(log10_nCount_RNA = log10(nCount_RNA + 1)) %>% 
  select(c('seurat_clusters', 'nFeature_RNA','log10_nCount_RNA','percent_mt','percent_rp')) %>% 
  reshape2::melt(id.vars = 'seurat_clusters') %>% 
  ggplot(mapping = aes(x = seurat_clusters, y = value)) +
  geom_violin(mapping = aes(fill = seurat_clusters), color = 'black', scale = 'width') +
  facet_wrap(. ~ variable, ncol = 2, scales = 'free_y') +
  theme_bw() +
  theme(legend.position = 'none')

p.summary <- (p.time | p.cluster) / p.metadata + patchwork::plot_layout(heights = c(1.5,1))
ggsave(filename = paste0(results_out, 'simple-merge_summary.tiff'), plot = p.summary, height = 9, width = 11, device = 'tiff')
```

```{r simple-default-deg}
default.deg <- FindAllMarkers(sc, logfc.threshold = 1, only.pos = TRUE)
top.deg.genes <- default.deg %>% 
  group_by(cluster) %>% 
  filter(p_val_adj < 10e-50) %>%
  top_n(n = 10, wt = -p_val_adj) %>% 
  top_n(n = 2, wt = avg_log2FC) %>% 
  ungroup()
p.markers <- DotPlot(
  object = sc, 
  assay = 'RNA', 
  features = unique(top.deg.genes$gene)
) +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(results_out, 'simple-merge_default-clusters_deg.tiff'), plot = p.markers, device = 'tiff', height = 10, width = 8)
```

```{r simple-canonical-markers}
canonical <- c('Slc17a6','Gad1','Gad2','Aqp4','Gfap','Olig1','Cspg4','Mbp','Csf1r','Ptprc','Col1a1','Vtn')
p.canonical <- DotPlot(sc, features = canonical) +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(results_out, 'simple-merge_default-clusters_canonical-markers.tiff'), plot = p.canonical, device = 'tiff', height = 4, width = 8)
```


## Integrated analysis

```{r integration-prep}
sc <- vector(mode = 'list', length = length(counts))
names(sc) <- names(counts)
for (i in 1:length(sc)) {
  sc[[i]] <- CreateSeuratObject(counts = counts[[i]], project = names(counts)[i])
  sc[[i]] <- PercentageFeatureSet(
    object = sc[[i]],
    pattern = '^mt-',
    col.name = 'percent_mt'
  )
  sc[[i]] <- PercentageFeatureSet(
    object = sc[[i]],
    pattern = 'Rp[ls]',
    col.name = 'percent_rp'
  )
  sc[[i]]$Time <- factor(
    x = sc[[i]]$orig.ident,
    levels = c('E19','P4','P8','P21')
  )
}
```


```{r integration}
sc <- lapply(
  X = sc,
  FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, nfeatures = 3000)
    return(x)
  }
)
anchor.features <- SelectIntegrationFeatures(sc, nfeatures = 2500)
anchors <- FindIntegrationAnchors(
  object.list = sc,
  anchor.features = anchor.features,
  normalization.method = 'LogNormalize'
)
sc <- IntegrateData(
  anchorset = anchors,
  normalization.method = 'LogNormalize',
)
DefaultAssay(sc)
sc <- sc %>% 
  ScaleData() %>% 
  RunPCA()
ElbowPlot(sc, ndims = 40)
sc <- sc %>% 
  FindNeighbors(dims = 1:15) %>% 
  FindClusters(resolution = 0.8) %>% 
  RunUMAP(dims = 1:15)
sc$Time <- factor(
  x = sc$orig.ident,
  levels = c('E19','P4','P8','P21')
)
```


```{r integrated-umap}
p.time <- DimPlot(sc, group.by = 'Time', shuffle = TRUE, pt.size = 0.75) +
  scale_color_manual(values = time.cols) +
  umap_theme + 
  guides(color = guide_legend(override.aes = list(size = 6))) + 
  theme(legend.text = element_text(size = 14))
p.cluster <- DimPlot(sc, group.by = 'seurat_clusters', label = TRUE, label.size = 5, repel = TRUE, pt.size = 0.75) + 
  umap_theme + 
  NoLegend()
p.metadata <- sc@meta.data %>% 
  mutate(log10_nCount_RNA = log10(nCount_RNA + 1)) %>% 
  select(c('seurat_clusters', 'nFeature_RNA','log10_nCount_RNA','percent_mt','percent_rp')) %>% 
  reshape2::melt(id.vars = 'seurat_clusters') %>% 
  ggplot(mapping = aes(x = seurat_clusters, y = value)) +
  geom_violin(mapping = aes(fill = seurat_clusters), color = 'black', scale = 'width') +
  facet_wrap(. ~ variable, ncol = 1, scales = 'free_y') +
  theme_bw() +
  theme(legend.position = 'none',
        strip.text = element_text(size = 10))
p.summary <- (p.time | p.cluster | p.metadata)
ggsave(filename = paste0(results_out, 'integrated_summary.tiff'), plot = p.summary, height = 6, width = 18.5, device = 'tiff')

p.summary
```


```{r integration-default-deg}
DefaultAssay(sc) <- 'RNA'
default.deg <- FindAllMarkers(sc, logfc.threshold = 1, only.pos = TRUE)
top.deg.genes <- default.deg %>% 
  group_by(cluster) %>% 
  filter(p_val_adj < 10e-50) %>%
  top_n(n = 10, wt = -p_val_adj) %>% 
  top_n(n = 2, wt = avg_log2FC) %>% 
  ungroup()
p.markers <- DotPlot(
  object = sc, 
  assay = 'RNA', 
  features = unique(top.deg.genes$gene)
) +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p.markers
ggsave(filename = paste0(results_out, 'integrated_default-clusters_deg.tiff'), plot = p.markers, device = 'tiff', height = 11, width = 9)
```


```{r celltype-annotation}
sc$celltype <- plyr::mapvalues(
  x = sc$integrated_snn_res.0.8,
  from = 0:29,
  to = c('Ex.Neuron',
         'Proto.Astrocyte',
         'In.Neuron',
         'In.Neuron',
         'In.Neuron',
         'In.Neuron',
         'Ex.Neuron',
         'Ex.Neuron',
         'In.Neuron',
         'Fibroblast',
         'In.Neuron',
         'In.Neuron',
         'Ex.Neuron',
         'OPC',
         'Ex.Neuron',
         'Ex.Neuron',
         'Ex.Neuron',
         'Ex.Neuron',
         'Fibro.Astrocyte',
         'Oligodendrocyte',
         'In.Neuron',
         'Ex.Neuron',
         'In.Neuron',
         'Ex.Neuron',
         'Ex.Neuron',
         'Dividing.Cells',
         'Cdh1.Ventricle.Cells',
         'Pre.Oligodendrocyte',
         'Microglia',
         'Endothelial')
)
sc$celltype <- factor(
  x = sc$celltype,
  levels = c('Ex.Neuron','In.Neuron','Proto.Astrocyte','Fibro.Astrocyte','OPC','Pre.Oligodendrocyte','Oligodendrocyte','Dividing.Cells','Microglia','Endothelial','Fibroblast','Cdh1.Ventricle.Cells')
)
p.celltype <- DimPlot(sc, group.by = 'celltype', label = TRUE, label.size = 5, pt.size = 1, repel = TRUE) +
  scale_color_manual(values = celltype.cols, name = 'Cell-type') + 
  umap_theme +
  theme(legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        plot.title = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 5)))
ggsave(filename = paste0(results_out, 'integrated_celltype.tiff'), plot = p.celltype, device = 'tiff', height = 6, width = 8)
ggsave(filename = paste0(results_out, 'integrated_celltype-time-umaps.tiff'), plot = (p.time | p.celltype), device = 'tiff', height = 6, width = 15)
p.celltype
```


```{r integrated-celltype-split-timepoint}
p.timesplit <- FetchData(sc, vars = c('celltype', 'Time', 'UMAP_1', 'UMAP_2')) %>%
  shuffle_rows() %>% 
  ggplot(mapping = aes(x = UMAP_1, y = UMAP_2)) +
  geom_point(mapping = aes(color = celltype), size = 0.75) +
  facet_grid(. ~ Time) +
  scale_color_manual(values = celltype.cols,
                     name = 'Cell-type') +
  umap_theme +
  theme(legend.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        axis.title = element_text(size = 14),
        strip.text = element_text(size = 14)) + 
  guides(color = guide_legend(override.aes = list(size = 5)))
p.timesplit
ggsave(filename = paste0(results_out, 'integrated_time-split.tiff'), plot = p.timesplit, device = 'tiff', height = 4, width = 16)
```


```{r celltype-proportion}
sc$Time <- factor(
  x = sc$Time,
  levels = c('E19','P4','P8','P21')
)
p.proportion <- prop.table(table('Celltype' = sc$celltype, 'Time' = sc$Time), margin = 2) %>% 
  data.frame() %>% 
  ggplot(mapping = aes(x = Time, y = Freq)) + 
  geom_bar(mapping = aes(fill = Celltype), stat = 'identity', color = 'black') +
  ylab(label = 'Proportion') +
  xlab(label = 'Time') +
  scale_fill_manual(values = celltype.cols) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.grid = element_blank())
p.proportion
ggsave(filename = paste0(results_out, 'integrated_celltype-proportions.tiff'),
       plot = p.proportion, device = 'tiff', height = 4, width = 5.5)
```



## Neuronal sub-type analysis

```{r neuron-subcluster-analysis}
DefaultAssay(sc) <- 'RNA'
neuron <- sc[, sc$celltype %in% c('Ex.Neuron','In.Neuron')]
neuron <- SplitObject(neuron, split.by = 'orig.ident')
neuron <- lapply(
  X = neuron,
  FUN = FindVariableFeatures,
  nfeatures = 3000
)
neuron.features <- SelectIntegrationFeatures(object.list = neuron, nfeatures = 1500)
anchors <- FindIntegrationAnchors(neuron, anchor.features = neuron.features, normalization.method = 'LogNormalize')
neuron <- IntegrateData(anchors, normalization.method = 'LogNormalize')
neuron <- neuron %>% 
  ScaleData() %>% 
  RunPCA()
ElbowPlot(neuron, ndims = 40)
pcs <- 1:10
neuron <- neuron %>% 
  FindNeighbors(dims = pcs) %>% 
  FindClusters(resolution = 0.8) %>% 
  RunUMAP(dims = pcs)
DefaultAssay(neuron) <- 'integrated'
neuron$Time <- factor(
  x = neuron$Time,
  levels = c('E19','P4','P8','P21')
)
```

```{r neuron-reclassification}
neuron$subtype <- neuron$integrated_snn_res.0.8
# neuron$subtype <- plyr::mapvalues(
#   x = neuron$integrated_snn_res.0.8,
#   from = levels(neuron$integrated_snn_res.0.8),
#   to = paste(c("ExN","InN","InN","InN","ExN","InN","ExN","InN","ExN","InN","ExN","ExN","ExN","ExN","InN","ExN","ExN","ExN","InN","InN","ExN","ExN","InN","ExN","InN","InN"), levels(neuron$integrated_snn_res.0.8), sep = '.')
# )
neuron$celltype_adjusted <- plyr::mapvalues(
  x = neuron$integrated_snn_res.0.8,
  from = levels(neuron$integrated_snn_res.0.8),
  to = c('Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Inhibitory.Neuron',
         'Inhibitory.Neuron',
         'Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Excitatory.Neuron',
         'Excitatory.Neuron',
         'Excitatory.Neuron',
         'Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Excitatory.Neuron',
         'Excitatory.Neuron',
         'Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Inhibitory.Neuron',
         'Excitatory.Neuron',
         'Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Excitatory.Neuron',
         'Inhibitory.Neuron',
         'Inhibitory.Neuron')
)
neuron$celltype_adjusted <- factor(
  x= neuron$celltype_adjusted,
  levels = c('Excitatory.Neuron', 'Inhibitory.Neuron')
)
names(neuron.cols) <- levels(neuron$subtype)
```


```{r neuron-default-summary}
p.neuron.time <- DimPlot(neuron, group.by = 'Time', shuffle = TRUE, pt.size = 1) +
  scale_color_manual(values = time.cols) +
  umap_theme + 
  labs(title = 'Time-point') +
  guides(color = guide_legend(override.aes = list(size = 6))) + 
  theme(legend.text = element_text(size = 14),
        plot.title = element_text(size = 16))
p.neuron.subtype <- DimPlot(neuron, group.by = 'subtype', label = TRUE, label.size = 5, repel = TRUE, pt.size = 0.75) + 
  scale_color_manual(values = neuron.cols) +
  umap_theme + 
  NoLegend() +
  labs(title = 'Neuronal sub-types') +
  theme(plot.title = element_text(size = 16))
p.neuron.celltype_adjusted <- DimPlot(neuron, group.by = 'celltype_adjusted', label = TRUE, label.size = 5, repel = TRUE, pt.size = 0.75) + 
  scale_color_manual(values = celltype.cols) +
  umap_theme + 
  NoLegend() +
  labs(title = 'Neuronal cell-type') +
  theme(plot.title = element_text(size = 16))
p.neuron.metadata <- neuron@meta.data %>% 
  mutate(log10_nCount_RNA = log10(nCount_RNA + 1)) %>% 
  select(c('subtype', 'nFeature_RNA','log10_nCount_RNA','percent_mt','percent_rp')) %>% 
  reshape2::melt(id.vars = 'subtype') %>% 
  ggplot(mapping = aes(x = subtype, y = value)) +
  geom_violin(mapping = aes(fill = subtype), color = 'black', scale = 'width') +
  scale_fill_manual(values = neuron.cols) +
  facet_wrap(. ~ variable, ncol = 1, scales = 'free_y') +
  theme_bw() +
  theme(legend.position = 'none',
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_text(size = 10))
p.neuron.summary <- (p.neuron.time | p.neuron.subtype | p.neuron.metadata)
ggsave(filename = paste0(results_out, 'neuron_summary.tiff'), plot = p.neuron.summary, device = 'tiff', height = 5.5, width = 15.5)
ggsave(filename = paste0(results_out, 'neuron_subtype-celltype_adjusted.tiff'), plot = (p.neuron.subtype | p.neuron.celltype_adjusted), device = 'tiff', height = 5.5, width = 11)

p.neuron.summary
```

```{r neuron-default-deg}
DefaultAssay(neuron) <- 'RNA'
neuron.deg <- FindAllMarkers(neuron, only.pos = TRUE)
write.csv(x = neuron.deg, file = paste0(results_out, 'neuron-subtype-deg.csv'))
```

```{r neuron-default-deg-dotplot}
neuron.top.deg <- neuron.deg %>% 
  group_by(cluster) %>% 
  top_n(n = 15, wt = -p_val_adj) %>% 
  top_n(n = 3, wt = avg_log2FC) %>% 
  ungroup() %>% 
  select('gene') %>% 
  unique()
p.neuron.markers <- DotPlot(neuron, assay = 'RNA', features = rev(unique(neuron.top.deg$gene))) +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(results_out, 'neuron_default-clusters_deg.tiff'),
       plot = p.neuron.markers, device = 'tiff', height = 12, width = 8.5)
```

```{r neuron-subtype-proportion}
neuron$Time <- factor(
  x = neuron$Time,
  levels = c('E19','P4','P8','P21')
)
p.neuron.proportion <- signif(prop.table(table('Subtype' = neuron$subtype, 'Time' = neuron$Time), margin = 2), digits = 3) %>% 
  data.frame() %>% 
  ggplot(mapping = aes(x = Time, y = Freq)) + 
  geom_bar(mapping = aes(fill = Subtype), stat = 'identity', color = 'black') +
  facet_wrap(. ~ Subtype, scales = 'free_y', ncol = 7) +
  ylab(label = 'Proportion') +
  xlab(label = 'Time') +
  scale_fill_manual(values = neuron.cols) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        strip.text = element_text(size = 14),
        panel.grid = element_blank(),
        legend.position = 'none')
p.neuron.proportion
ggsave(filename = paste0(results_out, 'neuron_subtype-proportions.tiff'),
       plot = p.neuron.proportion, device = 'tiff', height = 6.5, width = 13)
```

```{r neuron-subtype-time-composition}
prop.data <- table('Subtype' = neuron$subtype,
        'Time' = neuron$Time,
        'Celltype' = neuron$celltype_adjusted) %>% 
  data.frame() %>% 
  filter(Celltype == 'Excitatory.Neuron') %>% 
  group_by(Time) %>% 
  mutate(Freq = Freq / sum(Freq)) %>% 
  filter(Freq > 0) %>% 
  mutate(Subtype = droplevels(Subtype))
prop.cols <- neuron.cols[names(neuron.cols) %in% prop.data$Subtype]
p.ex.proportion <- prop.data %>%
  ggplot(mapping = aes(x = Time, y = Freq)) +
  geom_bar(mapping = aes(fill = Subtype), stat = 'identity', color = 'black') +
  scale_fill_manual(values = prop.cols, drop = TRUE) +
  labs(title = 'Excitatory neuron sub-type proportions') +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.grid = element_blank())
p.ex.proportion
ggsave(filename = paste0(results_out, 'neuron_ex-neuron-proportion.tiff'), plot = p.ex.proportion, device = 'tiff', height = 5.5, width = 5.5)

prop.data <- table('Subtype' = neuron$subtype,
        'Time' = neuron$Time,
        'Celltype' = neuron$celltype_adjusted) %>% 
  data.frame() %>% 
  filter(Celltype == 'Inhibitory.Neuron') %>% 
  group_by(Time) %>% 
  mutate(Freq = Freq / sum(Freq)) %>% 
  filter(Freq > 0) %>% 
  mutate(Subtype = droplevels(Subtype))
prop.cols <- neuron.cols[names(neuron.cols) %in% prop.data$Subtype]
p.in.proportion <- prop.data %>% 
  ggplot(mapping = aes(x = Time, y = Freq)) +
  geom_bar(mapping = aes(fill = Subtype), stat = 'identity', color = 'black') +
  scale_fill_manual(values = prop.cols) +
  labs(title = 'Inhibitory neuron sub-type proportions') +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.grid = element_blank())
p.in.proportion
ggsave(filename = paste0(results_out, 'neuron_in-neuron-proportion.tiff'), plot = p.in.proportion, device = 'tiff', height = 5.5, width = 5.5)


ex.prop.data <- round(prop.table(table(neuron$subtype[neuron$celltype_adjusted == 'Excitatory.Neuron'], neuron$Time[neuron$celltype_adjusted == 'Excitatory.Neuron']), margin = 2), digits = 4)
in.prop.data <- round(prop.table(table(neuron$subtype[neuron$celltype_adjusted == 'Inhibitory.Neuron'], neuron$Time[neuron$celltype_adjusted == 'Inhibitory.Neuron']), margin = 2), digits = 4)
write.csv(ex.prop.data, file = paste0(results_out, 'ExNeuron-subtype-proportions.csv'))
write.csv(in.prop.data, file = paste0(results_out, 'InNeuron-subtype-proportions.csv'))
```


## END
```{r}
sessionInfo()
```

